# Generated by Django 3.0.5 on 2025-04-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0001_initial'),
        ('store', '0006_auto_20250421_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBulkUpload',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bulk.bulkupload',),
        ),
    ]
