# Generated by Django 3.0.5 on 2025-04-21 20:28

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated_at')),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('task_name', models.CharField(max_length=256)),
                ('file_name', models.CharField(blank=True, max_length=256, null=True)),
                ('file_path', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('queue', 'Queue'), ('processing', 'Processing'), ('success', 'Success'), ('partially success', 'Partially Success'), ('failed', 'Failed')], max_length=64)),
                ('msg', models.CharField(blank=True, max_length=256, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_report', models.CharField(blank=True, max_length=256, null=True)),
                ('success_report', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
